// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using siddiq_6thassessment.Data;

#nullable disable

namespace siddiq_6thassessment.Migrations
{
    [DbContext(typeof(siddiq_6thassessmentContext))]
    partial class siddiq_6thassessmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("siddiq_6thassessment.model.Customer", b =>
                {
                    b.Property<int>("customerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("customerid"), 1L, 1);

                    b.Property<string>("customeraddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("customerphone")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("customerid");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("siddiq_6thassessment.model.Orders", b =>
                {
                    b.Property<int>("orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderid"), 1L, 1);

                    b.Property<float>("amount")
                        .HasColumnType("real");

                    b.Property<int?>("customerid")
                        .HasColumnType("int");

                    b.Property<int?>("productid")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("orderid");

                    b.HasIndex("customerid");

                    b.HasIndex("productid");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("siddiq_6thassessment.model.Product", b =>
                {
                    b.Property<int>("productid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productid"), 1L, 1);

                    b.Property<float?>("price")
                        .HasColumnType("real");

                    b.Property<string>("productname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("productid");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("siddiq_6thassessment.model.Orders", b =>
                {
                    b.HasOne("siddiq_6thassessment.model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("customerid");

                    b.HasOne("siddiq_6thassessment.model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productid");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
